### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Papiroso** [cycyrild/SebBypass#4]
Is it normal that such an error occurred when installing the extension?
<img width="700" alt="Снимок" src="https://github.com/user-attachments/assets/5ae49b39-bb81-4233-9b26-070b5345fa90" />

Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.

Help pls

**Comment by cycyrild** [comment]
Yes this is normal, it's just a warning because Chrome will stop supporting Manifest V2 extensions as used here.
Nothing to do with the extension itself.
